[package]
name = "lil-json"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-io = { version = "0.6.1", default-features = false }
numtoa = { version = "0.3.1", default-features = false }

[dev-dependencies]
embedded-io-adapters = { version = "0.6.2", default-features = false, features = ["std"] }
